### ISSUE TITLE
Puppet not installed on vagrant image and iptables problem

### ISSUE THREAD

**Issue by nickvth** [rafacas/vagrant-iscsi-target#1]
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.

Solution: use puppetlabs/centos-6.6-64-puppet

Vagrant.configure("2") do |config|
  config.vm.box = "puppetlabs/centos-6.6-64-puppet"

I also add to stop iptables to puppet config.

service {
    "iptables": ensure => "stopped";
}

**Comment by rafacas** [comment]
Thanks @nickvth! I've updated the Vagrantfile and puppet config to include your suggestions.
